/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kundan Pandey
 */
public class Facilitypanel extends javax.swing.JPanel {
    //totalprice=Fpackage.f_combo.getSelectedItem();

    int facPrice = 0;

    public Facilitypanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ac_hotel_cb = new javax.swing.JCheckBox();
        amusement_cb = new javax.swing.JCheckBox();
        ac_bus_cb = new javax.swing.JCheckBox();
        p_vehicle_cb = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        totalextrapric = new javax.swing.JTextField();
        facilitypanel_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tp_label = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Extra facilities :");

        ac_hotel_cb.setText("AC hotel");
        ac_hotel_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ac_hotel_cbItemStateChanged(evt);
            }
        });

        amusement_cb.setText("Amusement Park");
        amusement_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                amusement_cbItemStateChanged(evt);
            }
        });

        ac_bus_cb.setText("AC bus");
        ac_bus_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ac_bus_cbItemStateChanged(evt);
            }
        });

        p_vehicle_cb.setText("Personal vehicle");
        p_vehicle_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                p_vehicle_cbItemStateChanged(evt);
            }
        });

        jLabel1.setText("Total extra facility price:");

        totalextrapric.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        facilitypanel_button.setText("Next");
        facilitypanel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilitypanel_buttonActionPerformed(evt);
            }
        });

        jButton2.setText("Back");

        jLabel3.setText("Total Price");

        tp_label.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_vehicle_cb)
                            .addComponent(ac_bus_cb)
                            .addComponent(amusement_cb)
                            .addComponent(ac_hotel_cb)
                            .addComponent(totalextrapric, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(223, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(facilitypanel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ac_hotel_cb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amusement_cb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ac_bus_cb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p_vehicle_cb)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalextrapric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(facilitypanel_button))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ac_hotel_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ac_hotel_cbItemStateChanged
        if (ac_hotel_cb.isSelected() == true) {
            facPrice += 800;
        } else {
            facPrice -= 800;
        }
        totalextrapric.setText("" + facPrice);
        tp_label.setText("" + (facPrice + PackageFac.pricecombo));
        
    }//GEN-LAST:event_ac_hotel_cbItemStateChanged

    private void amusement_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_amusement_cbItemStateChanged
        if (amusement_cb.isSelected() == true) {
            facPrice += 100;
        } else {
            facPrice -= 100;
        }
        totalextrapric.setText("" + facPrice);
        tp_label.setText("" + (facPrice + PackageFac.pricecombo)); // TODO add your handling code here:
    }//GEN-LAST:event_amusement_cbItemStateChanged

    private void ac_bus_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ac_bus_cbItemStateChanged
        if (ac_bus_cb.isSelected() == true) {

            facPrice += 200;
        } else {
            facPrice -= 200;
        }
        totalextrapric.setText("" + facPrice);
        tp_label.setText("" + (facPrice + PackageFac.pricecombo));  // TODO add your handling code here:
    }//GEN-LAST:event_ac_bus_cbItemStateChanged

    private void p_vehicle_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_p_vehicle_cbItemStateChanged
        if (p_vehicle_cb.isSelected() == true) {
            facPrice += 800;
        } else {
            facPrice -= 800;
        }
        totalextrapric.setText("" + facPrice);
        tp_label.setText("" + (facPrice + PackageFac.pricecombo));
    }//GEN-LAST:event_p_vehicle_cbItemStateChanged

    private void facilitypanel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilitypanel_buttonActionPerformed
        PackageFac.feature.clear();

        if (ac_bus_cb.isSelected()) {
            PackageFac.feature.add("AC BUS");
        }
        if (ac_hotel_cb.isSelected()) {
            PackageFac.feature.add("AC HOTEL");
        }
        if (p_vehicle_cb.isSelected()) {
            PackageFac.feature.add("PERSONAL VEHICLE");
        }
        if (amusement_cb.isSelected()) {
            PackageFac.feature.add("AMUSEMENT");
        }
        PackageFac.total_amount=Integer.parseInt(tp_label.getText());
       
    }//GEN-LAST:event_facilitypanel_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ac_bus_cb;
    private javax.swing.JCheckBox ac_hotel_cb;
    private javax.swing.JCheckBox amusement_cb;
    private javax.swing.JButton facilitypanel_button;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox p_vehicle_cb;
    private javax.swing.JTextField totalextrapric;
    private javax.swing.JLabel tp_label;
    // End of variables declaration//GEN-END:variables
}
