
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kundan Pandey
 */
public class Flocpanel extends javax.swing.JPanel {

    Map<String, String> img = new HashMap<String, String>();

    Connection conn = null;

    /**
     * Creates new form flocpanel
     */
    public Flocpanel() {
        initComponents();
        conn = Databaseconnectivity.connectDatabase();
        locationfn();
    }

    private void locationfn() {
        try {

            Statement stmt = conn.createStatement();
            l_combo.removeAllItems();
            ResultSet rs = stmt.executeQuery("select Loc_name from location");
            while (rs.next()) {
                String lcombo = rs.getString("Loc_name");
                l_combo.addItem(lcombo);

            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        l_combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        location_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tourplacecombo = new javax.swing.JComboBox<>();
        imagelabel = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setPreferredSize(new java.awt.Dimension(511, 382));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Locations:\n");

        l_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        l_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l_comboMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selected location Tour Images:");

        location_button.setText("Next");
        location_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location_buttonActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tour places:");

        tourplacecombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tourplacecomboMouseReleased(evt);
            }
        });

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourismdb/Delhi/Qutab Minar.jpg.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tourplacecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_combo, 0, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(location_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(l_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tourplacecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(location_button)
                    .addComponent(jButton1))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void l_comboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_comboMousePressed

        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select Tour_name,img_path  from location where loc_name='" + l_combo.getSelectedItem().toString() + "'");
            while (rs.next()) {
                tourplacecombo.removeAllItems();
                String tour = rs.getString("Tour_name");
                String imagepath = rs.getString("img_path");
                String image[] = imagepath.split(",");
                String c[] = tour.split(",");
                for (int i = 0; i < c.length; i++) {
                    img.put(c[i], image[i]);
                    System.out.println(c[i]);
                    tourplacecombo.addItem(c[i]);
                }
            }
        } catch (SQLException e) {
            System.out.println(e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_l_comboMousePressed

    private void tourplacecomboMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tourplacecomboMouseReleased
       /* String path = "C:/Users/Kundan Pandey/Desktop/tourismdb/" + l_combo.getSelectedItem() + "/" + img.get(tourplacecombo.getSelectedItem().toString());
        ImageIcon icon = new ImageIcon(path);
        Image image = icon.getImage().getScaledInstance(imagelabel.getWidth(), imagelabel.getHeight(), Image.SCALE_SMOOTH);

        System.out.println(";gjdpathflkhjk" + path);
        imagelabel.setIcon(new ImageIcon(image));
        System.out.println(";gjdp running");*/
        
    }//GEN-LAST:event_tourplacecomboMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void location_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location_buttonActionPerformed
        PackageFac.location_name=(String) l_combo.getSelectedItem();
    }//GEN-LAST:event_location_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> l_combo;
    private javax.swing.JButton location_button;
    private javax.swing.JComboBox<String> tourplacecombo;
    // End of variables declaration//GEN-END:variables
}
