

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kundan Pandey
 */
public class Fpackage extends javax.swing.JPanel {

    Connection conn = null;

    /**
     * Creates new form fpackage
     */
    public Fpackage() {
        initComponents();
        conn = Databaseconnectivity.connectDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void familycombo() {
        try {
            Statement stmt = conn.createStatement();
            f_combo.removeAllItems();
            ResultSet rs = stmt.executeQuery("select price_family from package");
            while (rs.next()) {
                String familycombo = rs.getString("price_family");
                f_combo.addItem(familycombo);
            }
            JOptionPane.showMessageDialog(null, "MAXIMUM MEMBER ALLOWED:4");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void groupcombo() {
        try {
            Statement stmt = conn.createStatement();
            f_combo.removeAllItems();
            ResultSet rs = stmt.executeQuery("select price_group from package");
            while (rs.next()) {
                String familycombo = rs.getString("price_group");
                f_combo.addItem(familycombo);
            }
            JOptionPane.showMessageDialog(null, "MAXIMUM MEMBER ALLOWED:1");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void showDays() {
        PackageFac.pricecombo = Integer.parseInt(f_combo.getSelectedItem().toString());
        try {
            Statement st = conn.createStatement();
            ResultSet s = st.executeQuery("select numberofdays from package where price_group=" + f_combo.getSelectedItem().toString() + " or price_family=" + f_combo.getSelectedItem().toString() + "");
            while (s.next()) {
                String days = s.getString("numberofdays");
                num_days.setText(days);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        f_combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fmly_radio_btn = new javax.swing.JRadioButton();
        group_radio_btn = new javax.swing.JRadioButton();
        package_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        num_days = new javax.swing.JLabel();

        f_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                f_comboItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select Package :");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Select Package Type: ");

        buttonGroup1.add(fmly_radio_btn);
        fmly_radio_btn.setText("Family");
        fmly_radio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmly_radio_btnActionPerformed(evt);
            }
        });

        buttonGroup1.add(group_radio_btn);
        group_radio_btn.setText("Group");
        group_radio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group_radio_btnActionPerformed(evt);
            }
        });

        package_button.setBackground(new java.awt.Color(102, 102, 255));
        package_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        package_button.setForeground(new java.awt.Color(153, 51, 255));
        package_button.setText("Next");
        package_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                package_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("No. of days:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fmly_radio_btn)
                        .addGap(36, 36, 36)
                        .addComponent(group_radio_btn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(num_days, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(package_button)
                            .addComponent(f_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fmly_radio_btn)
                    .addComponent(group_radio_btn))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_combo))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(num_days, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(package_button)
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fmly_radio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmly_radio_btnActionPerformed
        try {
            familycombo();
        } catch (NullPointerException e) {
            fmly_radio_btn.doClick();
        }
    }//GEN-LAST:event_fmly_radio_btnActionPerformed

    private void group_radio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_group_radio_btnActionPerformed
        try {
            groupcombo();
        } catch (NullPointerException e) {
            group_radio_btn.doClick();
        }
    }//GEN-LAST:event_group_radio_btnActionPerformed

    private void f_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_f_comboItemStateChanged
        showDays();        // TODO add your handling code here:
    }//GEN-LAST:event_f_comboItemStateChanged

    private void package_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_package_buttonActionPerformed
        fmly_radio_btn.setActionCommand("Family");
        group_radio_btn.setActionCommand("Group");
        PackageFac.Pac_type = buttonGroup1.getSelection().getActionCommand();
        PackageFac.no_days = Integer.parseInt(num_days.getText());

    }//GEN-LAST:event_package_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> f_combo;
    private javax.swing.JRadioButton fmly_radio_btn;
    private javax.swing.JRadioButton group_radio_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel num_days;
    private javax.swing.JButton package_button;
    // End of variables declaration//GEN-END:variables
}
